# This config should be placed in following path:
#   ~/.local/share/io.parity.ethereum/config.toml

[parity]
# Kovan Test Network
chain = "kovan"
# Blockchain and settings will be stored in /media/jojo/LAB-4TB/Parity/Kovan.
# base_path = "/media/jojo/LAB-4TB/Parity/Kovan"
base_path = "/media/jojo/IvyMike/Parity/Kovan2"

[ui]
port = 7180

[network]
port = 20202

[rpc]
port = 7545


[dapps]
disable = false
port = 7080
interface = "local"
hosts = ["none"]
path = "/media/jojo/IvyMike/Parity/Dapps"

