# This config should be placed in following path:
#   ~/.local/share/io.parity.ethereum/config.toml

[parity]
# Kovan Test Network
chain = "kovan"
# Blockchain and settings will be stored in /media/jojo/LAB-4TB/Parity/Kovan.
# base_path = "/media/jojo/LAB-4TB/Parity/Kovan"
base_path = "/media/jojo/IvyMike/Parity/Kovan"


